from typing import Any, Dict, Optional

WORDING : Dict[str, Any] =\
{
	'conda_not_activated': 'Conda 未激活',
	'python_not_supported': 'Python 版本不受支持，请升级至 {version} 或更高版本',
	'curl_not_installed': 'cURL 未安装',
	'ffmpeg_not_installed': 'FFMpeg 未安装',
	'creating_temp': '正在创建临时资源',
	'extracting_frames': '正在提取分辨率为 {resolution} 且每秒 {fps} 帧的画面',
	'extracting_frames_succeed': '画面提取成功',
	'extracting_frames_failed': '画面提取失败',
	'analysing': '分析中',
	'extracting': '提取中',
	'streaming': '流式传输中',
	'processing': '处理中',
	'merging': '合并中',
	'downloading': '下载中',
	'temp_frames_not_found': '未找到临时画面',
	'copying_image': '正在复制分辨率为 {resolution} 的图像',
	'copying_image_succeed': '图像复制成功',
	'copying_image_failed': '图像复制失败',
	'finalizing_image': '正在完成分辨率为 {resolution} 的图像处理',
	'finalizing_image_succeed': '图像处理完成成功',
	'finalizing_image_skipped': '图像处理已跳过',
	'merging_video': '正在合并分辨率为 {resolution} 且每秒 {fps} 帧的视频',
	'merging_video_succeed': '视频合并成功',
	'merging_video_failed': '视频合并失败',
	'skipping_audio': '跳过音频处理',
	'replacing_audio_succeed': '音频替换成功',
	'replacing_audio_skipped': '音频替换已跳过',
	'restoring_audio_succeed': '音频恢复成功',
	'restoring_audio_skipped': '音频恢复已跳过',
	'clearing_temp': '正在清理临时资源',
	'processing_stopped': '处理已停止',
	'processing_image_succeed': '图像处理成功，耗时 {seconds} 秒',
	'processing_image_failed': '图像处理失败',
	'processing_video_succeed': '视频处理成功，耗时 {seconds} 秒',
	'processing_video_failed': '视频处理失败',
	'choose_image_source': '选择源图像',
	'choose_audio_source': '选择源音频',
	'choose_video_target': '选择目标视频',
	'choose_image_or_video_target': '选择目标图像或视频',
	'specify_image_or_video_output': '在目录中指定输出图像或视频',
	'match_target_and_output_extension': '目标文件与输出文件扩展名需一致',
	'no_source_face_detected': '未检测到源人脸',
	'processor_not_loaded': '处理器 {processor} 无法加载',
	'processor_not_implemented': '处理器 {processor} 未正确实现',
	'ui_layout_not_loaded': 'UI 布局 {ui_layout} 无法加载',
	'ui_layout_not_implemented': 'UI 布局 {ui_layout} 未正确实现',
	'stream_not_loaded': '流 {stream_mode} 无法加载',
	'stream_not_supported': '流模式不受支持',
	'job_created': '任务 {job_id} 已创建',
	'job_not_created': '任务 {job_id} 创建失败',
	'job_submitted': '任务 {job_id} 已提交',
	'job_not_submitted': '任务 {job_id} 提交失败',
	'job_all_submitted': '所有任务已提交',
	'job_all_not_submitted': '所有任务提交失败',
	'job_deleted': '任务 {job_id} 已删除',
	'job_not_deleted': '任务 {job_id} 删除失败',
	'job_all_deleted': '所有任务已删除',
	'job_all_not_deleted': '所有任务删除失败',
	'job_step_added': '步骤已添加到任务 {job_id}',
	'job_step_not_added': '步骤添加至任务 {job_id} 失败',
	'job_remix_step_added': '任务 {job_id} 的步骤 {step_index} 已重混',
	'job_remix_step_not_added': '任务 {job_id} 的步骤 {step_index} 重混失败',
	'job_step_inserted': '步骤 {step_index} 已插入任务 {job_id}',
	'job_step_not_inserted': '步骤 {step_index} 插入任务 {job_id} 失败',
	'job_step_removed': '步骤 {step_index} 已从任务 {job_id} 移除',
	'job_step_not_removed': '步骤 {step_index} 从任务 {job_id} 移除失败',
	'running_job': '正在运行队列中的任务 {job_id}',
	'running_jobs': '正在运行所有队列中的任务',
	'retrying_job': '正在重试失败的任务 {job_id}',
	'retrying_jobs': '正在重试所有失败的任务',
	'processing_job_succeed': '任务 {job_id} 处理成功',
	'processing_jobs_succeed': '所有任务处理成功',
	'processing_job_failed': '任务 {job_id} 处理失败',
	'processing_jobs_failed': '所有任务处理失败',
	'processing_step': '正在处理步骤 {step_current}/{step_total}',
	'validating_hash_succeed': '文件 {hash_file_name} 的哈希验证成功',
	'validating_hash_failed': '文件 {hash_file_name} 的哈希验证失败',
	'validating_source_succeed': '源文件 {source_file_name} 验证成功',
	'validating_source_failed': '源文件 {source_file_name} 验证失败',
	'deleting_corrupt_source': '正在删除损坏的源文件 {source_file_name}',
	'time_ago_now': '刚刚',
	'time_ago_minutes': '{minutes} 分钟前',
	'time_ago_hours': '{hours} 小时 {minutes} 分钟前',
	'time_ago_days': '{days} 天 {hours} 小时 {minutes} 分钟前',
	'point': '。',
	'comma': '，',
	'colon': '：',
	'question_mark': '？',
	'exclamation_mark': '！',
	'help':
	{
		# installer
		'install_dependency': '选择要安装的 {dependency} 版本',
		'skip_conda': '跳过 Conda 环境检查',
		# paths
		'config_path': '选择覆盖默认设置的配置文件',
		'temp_path': '指定临时资源的存储目录',
		'jobs_path': '指定任务存储目录',
		'source_paths': '选择图像或音频路径',
		'target_path': '选择图像或视频路径',
		'output_path': '在目录中指定输出图像或视频',
		# patterns
		'source_pattern': '选择图像或音频模式',
		'target_pattern': '选择图像或视频模式',
		'output_pattern': '指定图像或视频模式',
		# face detector
		'face_detector_model': '选择用于检测人脸的模型',
		'face_detector_size': '指定提供给面部检测器的帧尺寸',
		'face_detector_angles': '指定检测人脸前旋转画面的角度',
		'face_detector_score': '根据置信度分数筛选检测到的人脸',
		# face landmarker
		'face_landmarker_model': '选择用于检测面部关键点的模型',
		'face_landmarker_score': '根据置信度分数筛选检测到的面部关键点',
		# face selector
		'face_selector_mode': '使用基于参考的跟踪或简单匹配',
		'face_selector_order': '指定检测到的人脸排序方式',
		'face_selector_age_start': '根据起始年龄筛选检测到的人脸',
		'face_selector_age_end': '根据结束年龄筛选检测到的人脸',
		'face_selector_gender': '根据性别筛选检测到的人脸',
		'face_selector_race': '根据种族筛选检测到的人脸',
		'reference_face_position': '指定用于创建参考人脸的位置',
		'reference_face_distance': '指定参考人脸与目标人脸的相似度',
		'reference_frame_number': '指定用于创建参考人脸的帧编号',
		# face masker
		'face_occluder_model': '选择遮挡掩码模型',
		'face_parser_model': '选择区域掩码模型',
		'face_mask_types': '混合匹配不同人脸掩码类型（选项：{choices}）',
		'face_mask_areas': '选择用于区域掩码的项目（选项：{choices}）',
		'face_mask_regions': '选择用于区域掩码的项目（选项：{choices}）',
		'face_mask_blur': '指定应用于框掩码的模糊程度',
		'face_mask_padding': '对框掩码应用上、右、下、左内边距',
		# frame extraction
		'trim_frame_start': '指定目标视频的起始帧',
		'trim_frame_end': '指定目标视频的结束帧',
		'temp_frame_format': '指定临时资源的格式',
		'keep_temp': '处理完成后保留临时资源',
		# output creation
		'output_image_quality': '指定图像质量（影响压缩率）',
		'output_image_resolution': '根据目标图像指定输出分辨率',
		'output_audio_encoder': '指定音频编码器',
		'output_audio_quality': '指定音频质量（影响压缩率）',
		'output_audio_volume': '根据目标视频调整输出音量',
		'output_video_encoder': '指定视频编码器',
		'output_video_preset': '平衡视频处理速度和文件大小',
		'output_video_quality': '指定视频质量（影响压缩率）',
		'output_video_resolution': '根据目标视频指定输出分辨率',
		'output_video_fps': '根据目标视频指定输出帧率',
		# processors
		'processors': '加载单个或多个处理器（选项：{choices}, ...）',
		'age_modifier_model': '选择人脸年龄修改模型',
		'age_modifier_direction': '指定年龄修改方向',
		'deep_swapper_model': '选择人脸替换模型',
		'deep_swapper_morph': '在源人脸和目标人脸之间进行变形过渡',
		'expression_restorer_model': '选择表情恢复模型',
		'expression_restorer_factor': '从目标人脸恢复表情的强度',
		'face_debugger_items': '加载单个或多个调试项（选项：{choices}）',
		'face_editor_model': '选择人脸编辑模型',
		'face_editor_eyebrow_direction': '指定眉毛方向',
		'face_editor_eye_gaze_horizontal': '指定水平视线方向',
		'face_editor_eye_gaze_vertical': '指定垂直视线方向',
		'face_editor_eye_open_ratio': '指定眼睛张开比例',
		'face_editor_lip_open_ratio': '指定嘴唇张开比例',
		'face_editor_mouth_grim': '指定嘴巴紧绷程度',
		'face_editor_mouth_pout': '指定噘嘴程度',
		'face_editor_mouth_purse': '指定撇嘴程度',
		'face_editor_mouth_smile': '指定微笑程度',
		'face_editor_mouth_position_horizontal': '指定嘴巴水平位置',
		'face_editor_mouth_position_vertical': '指定嘴巴垂直位置',
		'face_editor_head_pitch': '指定头部俯仰角度',
		'face_editor_head_yaw': '指定头部偏航角度',
		'face_editor_head_roll': '指定头部滚动角度',
		'face_enhancer_model': '选择人脸增强模型',
		'face_enhancer_blend': '将增强结果融合到原始人脸',
		'face_enhancer_weight': '指定人脸增强权重',
		'face_swapper_model': '选择人脸替换模型',
		'face_swapper_pixel_boost': '选择人脸替换的像素增强分辨率',
		'frame_colorizer_model': '选择画面着色模型',
		'frame_colorizer_size': '指定提供给着色模型的帧尺寸',
		'frame_colorizer_blend': '将着色结果融合到原始画面',
		'frame_enhancer_model': '选择画面增强模型',
		'frame_enhancer_blend': '将增强结果融合到原始画面',
		'lip_syncer_model': '选择唇形同步模型',
		'lip_syncer_weight': '指定唇形同步权重',
		# uis
		'open_browser': '程序就绪后自动打开浏览器',
		'ui_layouts': '启动单个或多个UI布局（选项：{choices}, ...）',
		'ui_workflow': '选择UI工作流程',
		# download
		'download_providers': '使用不同提供方下载（选项：{choices}, ...）',
		'download_scope': '指定下载范围',
		# benchmark
		'benchmark_resolutions': '选择基准测试分辨率（选项：{choices}, ...）',
		'benchmark_cycle_count': '指定每个基准测试的循环次数',
		# execution
		'execution_device_id': '指定处理使用的设备',
		'execution_providers': '使用不同提供方推理（选项：{choices}, ...）',
		'execution_thread_count': '指定处理时的并行线程数',
		'execution_queue_count': '指定每个线程处理的帧数',
		# memory
		'video_memory_strategy': '平衡处理速度和显存占用',
		'system_memory_limit': '限制处理时可用的最大内存',
		# misc
		'log_level': '调整终端显示的消息严重级别',
		'halt_on_error': '发生错误时立即停止程序',
		# run
		'run': '运行程序',
		'headless_run': '无界面模式运行程序',
		'batch_run': '批量模式运行程序',
		'force_download': '强制自动下载并退出',
		'benchmark': '程序性能测试',
		# jobs
		'job_id': '指定任务ID',
		'job_status': '指定任务状态',
		'step_index': '指定步骤索引',
		# job manager
		'job_list': '按状态列出任务',
		'job_create': '创建草稿任务',
		'job_submit': '提交草稿任务为队列任务',
		'job_submit_all': '提交所有草稿任务为队列任务',
		'job_delete': '删除草稿/队列/失败/已完成任务',
		'job_delete_all': '删除所有任务',
		'job_add_step': '向草稿任务添加步骤',
		'job_remix_step': '重混草稿任务中的历史步骤',
		'job_insert_step': '向草稿任务插入步骤',
		'job_remove_step': '从草稿任务移除步骤',
		# job runner
		'job_run': '运行队列任务',
		'job_run_all': '运行所有队列任务',
		'job_retry': '重试失败任务',
		'job_retry_all': '重试所有失败任务'
	},
	'about':
	{
		'become_a_member': '成为会员',
		'join_our_community': '加入社区',
		'read_the_documentation': '阅读文档'
	},
	'uis':
	{
		'age_modifier_direction_slider': '年龄修改方向',
		'age_modifier_model_dropdown': '年龄修改模型',
		'apply_button': '应用',
		'benchmark_cycle_count_slider': '基准测试循环次数',
		'benchmark_resolutions_checkbox_group': '基准测试分辨率',
		'clear_button': '清除',
		'common_options_checkbox_group': '选项',
		'download_providers_checkbox_group': '下载提供方',
		'deep_swapper_model_dropdown': '深度换脸模型',
		'deep_swapper_morph_slider': '深度换脸变形度',
		'execution_providers_checkbox_group': '执行提供方',
		'execution_queue_count_slider': '执行队列数',
		'execution_thread_count_slider': '执行线程数',
		'expression_restorer_factor_slider': '表情恢复强度',
		'expression_restorer_model_dropdown': '表情恢复模型',
		'face_debugger_items_checkbox_group': '人脸调试项',
		'face_detector_angles_checkbox_group': '人脸检测角度',
		'face_detector_model_dropdown': '人脸检测模型',
		'face_detector_score_slider': '人脸检测置信度',
		'face_detector_size_dropdown': '人脸检测尺寸',
		'face_editor_eyebrow_direction_slider': '眉毛方向',
		'face_editor_eye_gaze_horizontal_slider': '水平视线',
		'face_editor_eye_gaze_vertical_slider': '垂直视线',
		'face_editor_eye_open_ratio_slider': '眼睛张开比例',
		'face_editor_head_pitch_slider': '头部俯仰角',
		'face_editor_head_roll_slider': '头部滚动角',
		'face_editor_head_yaw_slider': '头部偏航角',
		'face_editor_lip_open_ratio_slider': '嘴唇张开比例',
		'face_editor_model_dropdown': '人脸编辑模型',
		'face_editor_mouth_grim_slider': '嘴巴紧绷度',
		'face_editor_mouth_position_horizontal_slider': '嘴巴水平位置',
		'face_editor_mouth_position_vertical_slider': '嘴巴垂直位置',
		'face_editor_mouth_pout_slider': '噘嘴程度',
		'face_editor_mouth_purse_slider': '撇嘴程度',
		'face_editor_mouth_smile_slider': '微笑程度',
		'face_enhancer_blend_slider': '人脸融合度',
		'face_enhancer_model_dropdown': '人脸增强模型',
		'face_enhancer_weight_slider': '人脸增强权重',
		'face_landmarker_model_dropdown': '面部关键点模型',
		'face_landmarker_score_slider': '面部关键点置信度',
		'face_mask_blur_slider': '人脸掩码模糊度',
		'face_mask_padding_bottom_slider': '掩码底部内边距',
		'face_mask_padding_left_slider': '掩码左侧内边距',
		'face_mask_padding_right_slider': '掩码右侧内边距',
		'face_mask_padding_top_slider': '掩码顶部内边距',
		'face_mask_areas_checkbox_group': '人脸掩码区域',
		'face_mask_regions_checkbox_group': '人脸掩码分区',
		'face_mask_types_checkbox_group': '人脸掩码类型',
		'face_selector_age_range_slider': '人脸筛选年龄',
		'face_selector_gender_dropdown': '人脸筛选性别',
		'face_selector_mode_dropdown': '人脸筛选模式',
		'face_selector_order_dropdown': '人脸筛选顺序',
		'face_selector_race_dropdown': '人脸筛选种族',
		'face_swapper_model_dropdown': '人脸替换模型',
		'face_swapper_pixel_boost_dropdown': '像素增强分辨率',
		'face_occluder_model_dropdown': '人脸遮挡模型',
		'face_parser_model_dropdown': '人脸解析模型',
		'frame_colorizer_blend_slider': '画面着色融合度',
		'frame_colorizer_model_dropdown': '画面着色模型',
		'frame_colorizer_size_dropdown': '画面着色尺寸',
		'frame_enhancer_blend_slider': '画面增强融合度',
		'frame_enhancer_model_dropdown': '画面增强模型',
		'job_list_status_checkbox_group': '任务状态',
		'job_manager_job_action_dropdown': '任务操作',
		'job_manager_job_id_dropdown': '任务ID',
		'job_manager_step_index_dropdown': '步骤索引',
		'job_runner_job_action_dropdown': '任务操作',
		'job_runner_job_id_dropdown': '任务ID',
		'lip_syncer_model_dropdown': '唇形同步模型',
		'lip_syncer_weight_slider': '唇形同步权重',
		'log_level_dropdown': '日志级别',
		'output_audio_encoder_dropdown': '输出音频编码器',
		'output_audio_quality_slider': '输出音频质量',
		'output_audio_volume_slider': '输出音频音量',
		'output_image_or_video': '输出',
		'output_image_quality_slider': '输出图像质量',
		'output_image_resolution_dropdown': '输出图像分辨率',
		'output_path_textbox': '输出路径',
		'output_video_encoder_dropdown': '输出视频编码器',
		'output_video_fps_slider': '输出视频帧率',
		'output_video_preset_dropdown': '输出视频预设',
		'output_video_quality_slider': '输出视频质量',
		'output_video_resolution_dropdown': '输出视频分辨率',
		'preview_frame_slider': '预览帧',
		'preview_image': '预览',
		'processors_checkbox_group': '处理器',
		'reference_face_distance_slider': '参考人脸相似度',
		'reference_face_gallery': '参考人脸',
		'refresh_button': '刷新',
		'source_file': '源文件',
		'start_button': '开始',
		'stop_button': '停止',
		'system_memory_limit_slider': '系统内存限制',
		'target_file': '目标文件',
		'temp_frame_format_dropdown': '临时帧格式',
		'terminal_textbox': '终端',
		'trim_frame_slider': '截取帧范围',
		'ui_workflow': 'UI工作流程',
		'video_memory_strategy_dropdown': '显存策略',
		'webcam_fps_slider': '摄像头帧率',
		'webcam_image': '摄像头画面',
		'webcam_device_id_dropdown': '摄像头设备ID',
		'webcam_mode_radio': '摄像头模式',
		'webcam_resolution_dropdown': '摄像头分辨率'
	}
}


def get(notation : str) -> Optional[str]:
	current = WORDING

	for fragment in notation.split('.'):
		if fragment in current:
			current = current.get(fragment)
			if isinstance(current, str):
				return current

	return None